// 4xx
export const BAD_REQUEST = 'BAD_REQUEST'
export const NOT_FOUND = 'NOT_FOUND'
export const FORBIDDEN = 'FORBIDDEN'
export const UNAUTHORIZED = 'UNAUTHORIZED'

// 5xx
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
